const tooltipData: Record<string, TooltipEntry> = {
  'resource-credits': {
    title: 'Credits',
    content: 'The primary currency used for construction, maintenance, and trade. Generated by colonies and trade routes.',
    hint: 'Build Trading Posts to increase income',
    stats: [
      { icon: '🏭', name: 'From Colonies',  value: '+45/turn', positive: true },
      { icon: '📦', name: 'Trade Routes',   value: '+12/turn', positive: true },
      { icon: '🔧', name: 'Maintenance',    value: '-18/turn', negative: true },
    ],
  },
  'resource-dilithium': {
    title: 'Dilithium',
    content: 'Rare crystal used to regulate matter/antimatter reactions in warp cores. Essential for ship construction.',
    hint: 'Found in asteroid fields and some planets',
  },
  'resource-duranium': {
    title: 'Duranium',
    content: 'Heavy metal alloy used in ship hulls and defensive structures. Mined from planetary deposits.',
    hint: 'Build Mining Facilities to increase production',
  },
  'resource-research': {
    title: 'Research Points',
    content: 'Scientific output used to unlock new technologies. Generated by laboratories and science vessels.',
    hint: 'Assign scientists to labs for bonus output',
  },
  'ship-scout': {
    title: 'Scout',
    content: 'Fast reconnaissance vessel ideal for exploration. Lightly armed but highly maneuverable.',
    stats: [
      { icon: '⚔', name: 'Attack',  value: '30' },
      { icon: '🛡', name: 'Defense', value: '15' },
      { icon: '💨', name: 'Speed',   value: '18' },
    ],
  },
  'ship-destroyer': {
    title: 'Destroyer',
    content: 'Light combat vessel designed for patrol and escort duties. Good balance of firepower and speed.',
    stats: [
      { icon: '⚔', name: 'Attack',  value: '60' },
      { icon: '🛡', name: 'Defense', value: '30' },
      { icon: '💨', name: 'Speed',   value: '12' },
    ],
  },
  'ship-cruiser': {
    title: 'Cruiser',
    content: 'Main battle vessel forming the backbone of any fleet. Versatile and well-armored.',
    stats: [
      { icon: '⚔', name: 'Attack',  value: '100' },
      { icon: '🛡', name: 'Defense', value: '50' },
      { icon: '💨', name: 'Speed',   value: '8' },
    ],
  },
  'ship-battleship': {
    title: 'Battleship',
    content: 'Heavy warship with devastating firepower. Slow but extremely powerful in combat.',
    stats: [
      { icon: '⚔', name: 'Attack',  value: '200' },
      { icon: '🛡', name: 'Defense', value: '100' },
      { icon: '💨', name: 'Speed',   value: '5' },
    ],
  },
  'building-shipyard': {
    title: 'Orbital Shipyard',
    content: 'Enables construction of starships at this colony. Higher levels allow larger ship classes.',
    hint: 'Upgrade to build capital ships',
  },
  'building-research-lab': {
    title: 'Research Laboratory',
    content: 'Facility dedicated to scientific research. Increases research output of the colony.',
    stats: [
      { icon: '🔬', name: 'Research',    value: '+10',      positive: true },
      { icon: '💰', name: 'Maintenance', value: '-5/turn',  negative: true },
    ],
  },
  'building-factory': {
    title: 'Industrial Complex',
    content: 'Manufacturing facility that increases production capacity.',
    stats: [
      { icon: '🏭', name: 'Production', value: '+15', positive: true },
    ],
  },
  'action-end-turn': {
    title: 'End Turn',
    content: 'Submit your orders and advance to the next turn. All queued actions will be processed.',
    hint: 'Make sure all fleets have orders!',
  },
  'action-research': {
    title: 'Select Research',
    content: 'Choose a technology to research. Progress is made each turn based on your science output.',
  },
  'diplomacy-trade': {
    title: 'Trade Agreement',
    content: 'Establish trade routes between empires, providing mutual economic benefits.',
    stats: [
      { icon: '💰', name: 'Credits', value: '+10/turn', positive: true },
      { icon: '👍', name: 'Opinion', value: '+25',      positive: true },
    ],
  },
  'diplomacy-nap': {
    title: 'Non-Aggression Pact',
    content: 'A formal agreement to refrain from hostile actions. Provides security but limits expansion options.',
    stats: [
      { icon: '👍', name: 'Opinion', value: '+15', positive: true },
    ],
  },
  'diplomacy-alliance': {
    title: 'Defensive Alliance',
    content: 'Military alliance providing mutual defense. Allies will join wars if either is attacked.',
    stats: [
      { icon: '👍', name: 'Opinion', value: '+50',    positive: true },
      { icon: '⚔',  name: 'Defense', value: 'Shared' },
    ],
  },
};

let tooltipComponent: DotNetObjectReference | null = null;
let showTimeout: ReturnType<typeof setTimeout> | null = null;
let hideTimeout: ReturnType<typeof setTimeout> | null = null;

function init(componentRef: DotNetObjectReference): void {
  tooltipComponent = componentRef;
  document.addEventListener('mouseover', handleMouseOver);
  document.addEventListener('mouseout',  handleMouseOut);
  document.addEventListener('mousemove', handleMouseMove);
}

function handleMouseOver(e: MouseEvent): void {
  const target = (e.target as Element).closest<HTMLElement>('[data-tooltip]');
  if (!target) return;

  if (hideTimeout !== null) clearTimeout(hideTimeout);

  showTimeout = setTimeout(() => {
    const tooltipKey = target.getAttribute('data-tooltip') ?? '';
    const data = tooltipData[tooltipKey];

    if (data && tooltipComponent) {
      void tooltipComponent.invokeMethodAsync(
        'Show',
        e.clientX, e.clientY,
        data.title,
        data.content,
        data.hint ?? '',
        data.stats ?? null,
      );
    } else if (tooltipComponent) {
      void tooltipComponent.invokeMethodAsync(
        'Show',
        e.clientX, e.clientY,
        target.getAttribute('data-tooltip-title')   ?? '',
        target.getAttribute('data-tooltip-content') ?? tooltipKey,
        target.getAttribute('data-tooltip-hint')    ?? '',
        null,
      );
    }
  }, 300);
}

function handleMouseOut(e: MouseEvent): void {
  const target = (e.target as Element).closest('[data-tooltip]');
  if (!target) return;

  if (showTimeout !== null) clearTimeout(showTimeout);
  hideTimeout = setTimeout(() => {
    tooltipComponent?.invokeMethodAsync('Hide');
  }, 100);
}

function handleMouseMove(e: MouseEvent): void {
  tooltipComponent?.invokeMethodAsync('Move', e.clientX, e.clientY);
}

window.GameTooltips = {
  init,
  addTooltipData(key: string, data: TooltipEntry): void {
    tooltipData[key] = data;
  },
};
